import Home from "./Home";
import Contact from "./Contact";
import Movies from "./Movies";
import NotFound from "./NotFound";
import TvSeries from "./TvSeries";
import Detail from "./Detail";
import OurStory from "./OurStory";
import Login from "./Login";
import Profile from "./Profile";
export { Home, Contact, Movies, NotFound, TvSeries, Detail, OurStory, Login, Profile };
